FORMAT: 1A
HOST: http://tidepool.io

# tidepool-user-api
The Tidepool User API is used to manage the user login information and pretty much nothing else.
Temporarily, it also manages sessions. That will change.

# Group User
User related resources of the **User API**

## Login [/login]
### Log in an existing user [POST]
+ Request

    + Headers
    
            X-Tidepool-UserID: {username}
            X-Tidepool-Password: {password}
            

+ Response 200 (application/json)

    + Headers

            x-tidepool-session-token : 1324234234.adfa234.123ad34

    + Body
    
            {
              "userid": "123123abcd",
              "username": {username},
              "emails" : [ "email1@foo.com" ]
            }

    
## User records [/user]
### Retrieve current user's info [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
